input = "./spec"
output = "./tooling/minirust-rs"
name = "minirust-rs"
attrs = [
    '#![recursion_limit = "256"]',
    '#![feature(yeet_expr)]',
    '#![feature(never_type)]',
    '#![feature(iterator_try_collect)]',
    '#![feature(const_option)]',
    '#![feature(try_blocks)]',
]
