input = "./spec"
output = "./tooling/gen-minirust"
name = "gen-minirust"
channel = "nightly-2023-06-01" # FIXME: remove this, it is redundant with the tooling/rust-toolchain.toml file
attrs = [
    '#![recursion_limit = "256"]',
    '#![feature(yeet_expr)]',
    '#![feature(never_type)]',
    '#![feature(iterator_try_collect)]',
    '#![feature(const_option)]',
    '#![feature(try_blocks)]',
]
